# This is a basic workflow to help you get started with Actions

name: Upload Logic App

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ['Azure Bicep']
    types: [completed]

jobs:
    Build:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - uses: actions/checkout@v2
        - name: replace connections.json
          uses: canastro/copy-file-action@master
          with:
            source: connections.deploy.json
            target: connections.json        
        - name: Easy Zip Files
          uses: vimtor/action-zip@v1
          with:
            dest: ${{ github.run_id }}.zip
            files: ./
        - uses: actions/upload-artifact@master
          with:
            name: build-artifact
            path: ${{ github.run_id }}.zip
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: [Build] 
      steps:
       - uses: azure/login@v1
         with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

       - name: Get publish profile
         uses: Azure/powershell@v1
         id: pp
         with:
           inlineScript: |
             $publishprofile = Get-AzWebAppPublishingProfile -ResourceGroupName "${{ secrets.AZURE_RG }}" -Name "${{secrets.LA_NAME}}" -Format "WebDeploy"
             $publishprofile = $publishprofile.Replace("`r","").Replace("`n","")
             echo "::set-output name=publish_profile::$publishprofile"
           azPSVersion:  "latest"
            
       - uses: actions/download-artifact@master
         with:
          name: build-artifact
          path: build-art/

       - name: Deploy to Azure Logic App
         uses: Azure/functions-action@v1.4.4
         id: la
         with:
          app-name: ${{secrets.LA_NAME}}
          package: build-art/${{ github.run_id }}.zip
          publish-profile: ${{steps.pp.outputs.publish_profile}}
